# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cd5abb0848693cd69a25d025bb77ef57c50d7780503099c50c3f6e6f2ce2f20ee017d08b0eb9a861fc2164d4fcc307eddfbd555bbb8bcf5454ec7b649336a22a

test:
  secret_key_base: bd787af613dcfc18022ebc1db7becfcb278dd92a94085355779a4dc02094333187624e67c5af0b38debf709c8bec2b54958f0de2a628e45149a5ae2e6c01bbec

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
